<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('currencies')->insert(
            [
                [
                    'id'              => 0,
                    'currency_name'   => 'No universal currency',
                    'alphabetic_code' => '',
                    'numeric_code'    => '',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 8,
                    'currency_name'   => 'Lek',
                    'alphabetic_code' => 'ALL',
                    'numeric_code'    => '008',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 12,
                    'currency_name'   => 'Algerian Dinar',
                    'alphabetic_code' => 'DZD',
                    'numeric_code'    => '012',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 32,
                    'currency_name'   => 'Argentine Peso',
                    'alphabetic_code' => 'ARS',
                    'numeric_code'    => '032',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 36,
                    'currency_name'   => 'Australian Dollar',
                    'alphabetic_code' => 'AUD',
                    'numeric_code'    => '036',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 44,
                    'currency_name'   => 'Bahamian Dollar',
                    'alphabetic_code' => 'BSD',
                    'numeric_code'    => '044',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 48,
                    'currency_name'   => 'Bahraini Dinar',
                    'alphabetic_code' => 'BHD',
                    'numeric_code'    => '048',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 50,
                    'currency_name'   => 'Taka',
                    'alphabetic_code' => 'BDT',
                    'numeric_code'    => '050',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 51,
                    'currency_name'   => 'Armenian Dram',
                    'alphabetic_code' => 'AMD',
                    'numeric_code'    => '051',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 52,
                    'currency_name'   => 'Barbados Dollar',
                    'alphabetic_code' => 'BBD',
                    'numeric_code'    => '052',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 60,
                    'currency_name'   => 'Bermudian Dollar',
                    'alphabetic_code' => 'BMD',
                    'numeric_code'    => '060',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 64,
                    'currency_name'   => 'Ngultrum',
                    'alphabetic_code' => 'BTN',
                    'numeric_code'    => '064',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 68,
                    'currency_name'   => 'Boliviano',
                    'alphabetic_code' => 'BOB',
                    'numeric_code'    => '068',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 72,
                    'currency_name'   => 'Pula',
                    'alphabetic_code' => 'BWP',
                    'numeric_code'    => '072',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 84,
                    'currency_name'   => 'Belize Dollar',
                    'alphabetic_code' => 'BZD',
                    'numeric_code'    => '084',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 90,
                    'currency_name'   => 'Solomon Islands Dollar',
                    'alphabetic_code' => 'SBD',
                    'numeric_code'    => '090',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 96,
                    'currency_name'   => 'Brunei Dollar',
                    'alphabetic_code' => 'BND',
                    'numeric_code'    => '096',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 104,
                    'currency_name'   => 'Kyat',
                    'alphabetic_code' => 'MMK',
                    'numeric_code'    => '104',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 108,
                    'currency_name'   => 'Burundi Franc',
                    'alphabetic_code' => 'BIF',
                    'numeric_code'    => '108',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 116,
                    'currency_name'   => 'Riel',
                    'alphabetic_code' => 'KHR',
                    'numeric_code'    => '116',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 124,
                    'currency_name'   => 'Canadian Dollar',
                    'alphabetic_code' => 'CAD',
                    'numeric_code'    => '124',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 132,
                    'currency_name'   => 'Cabo Verde Escudo',
                    'alphabetic_code' => 'CVE',
                    'numeric_code'    => '132',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 136,
                    'currency_name'   => 'Cayman Islands Dollar',
                    'alphabetic_code' => 'KYD',
                    'numeric_code'    => '136',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 144,
                    'currency_name'   => 'Sri Lanka Rupee',
                    'alphabetic_code' => 'LKR',
                    'numeric_code'    => '144',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 152,
                    'currency_name'   => 'Chilean Peso',
                    'alphabetic_code' => 'CLP',
                    'numeric_code'    => '152',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 156,
                    'currency_name'   => 'Yuan Renminbi',
                    'alphabetic_code' => 'CNY',
                    'numeric_code'    => '156',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 170,
                    'currency_name'   => 'Colombian Peso',
                    'alphabetic_code' => 'COP',
                    'numeric_code'    => '170',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 174,
                    'currency_name'   => 'Comorian Franc ',
                    'alphabetic_code' => 'KMF',
                    'numeric_code'    => '174',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 188,
                    'currency_name'   => 'Costa Rican Colon',
                    'alphabetic_code' => 'CRC',
                    'numeric_code'    => '188',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 192,
                    'currency_name'   => 'Cuban Peso',
                    'alphabetic_code' => 'CUP',
                    'numeric_code'    => '192',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 203,
                    'currency_name'   => 'Czech Koruna',
                    'alphabetic_code' => 'CZK',
                    'numeric_code'    => '203',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 208,
                    'currency_name'   => 'Danish Krone',
                    'alphabetic_code' => 'DKK',
                    'numeric_code'    => '208',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 214,
                    'currency_name'   => 'Dominican Peso',
                    'alphabetic_code' => 'DOP',
                    'numeric_code'    => '214',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 222,
                    'currency_name'   => 'El Salvador Colon',
                    'alphabetic_code' => 'SVC',
                    'numeric_code'    => '222',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 230,
                    'currency_name'   => 'Ethiopian Birr',
                    'alphabetic_code' => 'ETB',
                    'numeric_code'    => '230',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 232,
                    'currency_name'   => 'Nakfa',
                    'alphabetic_code' => 'ERN',
                    'numeric_code'    => '232',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 238,
                    'currency_name'   => 'Falkland Islands Pound',
                    'alphabetic_code' => 'FKP',
                    'numeric_code'    => '238',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 242,
                    'currency_name'   => 'Fiji Dollar',
                    'alphabetic_code' => 'FJD',
                    'numeric_code'    => '242',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 262,
                    'currency_name'   => 'Djibouti Franc',
                    'alphabetic_code' => 'DJF',
                    'numeric_code'    => '262',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 270,
                    'currency_name'   => 'Dalasi',
                    'alphabetic_code' => 'GMD',
                    'numeric_code'    => '270',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 292,
                    'currency_name'   => 'Gibraltar Pound',
                    'alphabetic_code' => 'GIP',
                    'numeric_code'    => '292',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 320,
                    'currency_name'   => 'Quetzal',
                    'alphabetic_code' => 'GTQ',
                    'numeric_code'    => '320',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 324,
                    'currency_name'   => 'Guinean Franc',
                    'alphabetic_code' => 'GNF',
                    'numeric_code'    => '324',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 328,
                    'currency_name'   => 'Guyana Dollar',
                    'alphabetic_code' => 'GYD',
                    'numeric_code'    => '328',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 332,
                    'currency_name'   => 'Gourde',
                    'alphabetic_code' => 'HTG',
                    'numeric_code'    => '332',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 340,
                    'currency_name'   => 'Lempira',
                    'alphabetic_code' => 'HNL',
                    'numeric_code'    => '340',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 344,
                    'currency_name'   => 'Hong Kong Dollar',
                    'alphabetic_code' => 'HKD',
                    'numeric_code'    => '344',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 348,
                    'currency_name'   => 'Forint',
                    'alphabetic_code' => 'HUF',
                    'numeric_code'    => '348',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 352,
                    'currency_name'   => 'Iceland Krona',
                    'alphabetic_code' => 'ISK',
                    'numeric_code'    => '352',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 356,
                    'currency_name'   => 'Indian Rupee',
                    'alphabetic_code' => 'INR',
                    'numeric_code'    => '356',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 360,
                    'currency_name'   => 'Rupiah',
                    'alphabetic_code' => 'IDR',
                    'numeric_code'    => '360',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 364,
                    'currency_name'   => 'Iranian Rial',
                    'alphabetic_code' => 'IRR',
                    'numeric_code'    => '364',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 368,
                    'currency_name'   => 'Iraqi Dinar',
                    'alphabetic_code' => 'IQD',
                    'numeric_code'    => '368',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 376,
                    'currency_name'   => 'New Israeli Sheqel',
                    'alphabetic_code' => 'ILS',
                    'numeric_code'    => '376',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 388,
                    'currency_name'   => 'Jamaican Dollar',
                    'alphabetic_code' => 'JMD',
                    'numeric_code'    => '388',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 392,
                    'currency_name'   => 'Yen',
                    'alphabetic_code' => 'JPY',
                    'numeric_code'    => '392',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 398,
                    'currency_name'   => 'Tenge',
                    'alphabetic_code' => 'KZT',
                    'numeric_code'    => '398',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 400,
                    'currency_name'   => 'Jordanian Dinar',
                    'alphabetic_code' => 'JOD',
                    'numeric_code'    => '400',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 404,
                    'currency_name'   => 'Kenyan Shilling',
                    'alphabetic_code' => 'KES',
                    'numeric_code'    => '404',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 408,
                    'currency_name'   => 'North Korean Won',
                    'alphabetic_code' => 'KPW',
                    'numeric_code'    => '408',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 410,
                    'currency_name'   => 'Won',
                    'alphabetic_code' => 'KRW',
                    'numeric_code'    => '410',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 414,
                    'currency_name'   => 'Kuwaiti Dinar',
                    'alphabetic_code' => 'KWD',
                    'numeric_code'    => '414',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 417,
                    'currency_name'   => 'Som',
                    'alphabetic_code' => 'KGS',
                    'numeric_code'    => '417',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 418,
                    'currency_name'   => 'Lao Kip',
                    'alphabetic_code' => 'LAK',
                    'numeric_code'    => '418',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 422,
                    'currency_name'   => 'Lebanese Pound',
                    'alphabetic_code' => 'LBP',
                    'numeric_code'    => '422',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 426,
                    'currency_name'   => 'Loti',
                    'alphabetic_code' => 'LSL',
                    'numeric_code'    => '426',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 430,
                    'currency_name'   => 'Liberian Dollar',
                    'alphabetic_code' => 'LRD',
                    'numeric_code'    => '430',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 434,
                    'currency_name'   => 'Libyan Dinar',
                    'alphabetic_code' => 'LYD',
                    'numeric_code'    => '434',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 446,
                    'currency_name'   => 'Pataca',
                    'alphabetic_code' => 'MOP',
                    'numeric_code'    => '446',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 454,
                    'currency_name'   => 'Malawi Kwacha',
                    'alphabetic_code' => 'MWK',
                    'numeric_code'    => '454',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 458,
                    'currency_name'   => 'Malaysian Ringgit',
                    'alphabetic_code' => 'MYR',
                    'numeric_code'    => '458',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 462,
                    'currency_name'   => 'Rufiyaa',
                    'alphabetic_code' => 'MVR',
                    'numeric_code'    => '462',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 480,
                    'currency_name'   => 'Mauritius Rupee',
                    'alphabetic_code' => 'MUR',
                    'numeric_code'    => '480',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 484,
                    'currency_name'   => 'Mexican Peso',
                    'alphabetic_code' => 'MXN',
                    'numeric_code'    => '484',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 496,
                    'currency_name'   => 'Tugrik',
                    'alphabetic_code' => 'MNT',
                    'numeric_code'    => '496',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 498,
                    'currency_name'   => 'Moldovan Leu',
                    'alphabetic_code' => 'MDL',
                    'numeric_code'    => '498',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 504,
                    'currency_name'   => 'Moroccan Dirham',
                    'alphabetic_code' => 'MAD',
                    'numeric_code'    => '504',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 512,
                    'currency_name'   => 'Rial Omani',
                    'alphabetic_code' => 'OMR',
                    'numeric_code'    => '512',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 516,
                    'currency_name'   => 'Namibia Dollar',
                    'alphabetic_code' => 'NAD',
                    'numeric_code'    => '516',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 524,
                    'currency_name'   => 'Nepalese Rupee',
                    'alphabetic_code' => 'NPR',
                    'numeric_code'    => '524',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 532,
                    'currency_name'   => 'Netherlands Antillean Guilder',
                    'alphabetic_code' => 'ANG',
                    'numeric_code'    => '532',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 533,
                    'currency_name'   => 'Aruban Florin',
                    'alphabetic_code' => 'AWG',
                    'numeric_code'    => '533',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 548,
                    'currency_name'   => 'Vatu',
                    'alphabetic_code' => 'VUV',
                    'numeric_code'    => '548',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 554,
                    'currency_name'   => 'New Zealand Dollar',
                    'alphabetic_code' => 'NZD',
                    'numeric_code'    => '554',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 558,
                    'currency_name'   => 'Cordoba Oro',
                    'alphabetic_code' => 'NIO',
                    'numeric_code'    => '558',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 566,
                    'currency_name'   => 'Naira',
                    'alphabetic_code' => 'NGN',
                    'numeric_code'    => '566',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 578,
                    'currency_name'   => 'Norwegian Krone',
                    'alphabetic_code' => 'NOK',
                    'numeric_code'    => '578',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 586,
                    'currency_name'   => 'Pakistan Rupee',
                    'alphabetic_code' => 'PKR',
                    'numeric_code'    => '586',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 590,
                    'currency_name'   => 'Balboa',
                    'alphabetic_code' => 'PAB',
                    'numeric_code'    => '590',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 598,
                    'currency_name'   => 'Kina',
                    'alphabetic_code' => 'PGK',
                    'numeric_code'    => '598',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 600,
                    'currency_name'   => 'Guarani',
                    'alphabetic_code' => 'PYG',
                    'numeric_code'    => '600',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 604,
                    'currency_name'   => 'Sol',
                    'alphabetic_code' => 'PEN',
                    'numeric_code'    => '604',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 608,
                    'currency_name'   => 'Philippine Peso',
                    'alphabetic_code' => 'PHP',
                    'numeric_code'    => '608',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 634,
                    'currency_name'   => 'Qatari Rial',
                    'alphabetic_code' => 'QAR',
                    'numeric_code'    => '634',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 643,
                    'currency_name'   => 'Russian Ruble',
                    'alphabetic_code' => 'RUB',
                    'numeric_code'    => '643',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 646,
                    'currency_name'   => 'Rwanda Franc',
                    'alphabetic_code' => 'RWF',
                    'numeric_code'    => '646',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 654,
                    'currency_name'   => 'Saint Helena Pound',
                    'alphabetic_code' => 'SHP',
                    'numeric_code'    => '654',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 682,
                    'currency_name'   => 'Saudi Riyal',
                    'alphabetic_code' => 'SAR',
                    'numeric_code'    => '682',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 690,
                    'currency_name'   => 'Seychelles Rupee',
                    'alphabetic_code' => 'SCR',
                    'numeric_code'    => '690',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 694,
                    'currency_name'   => 'Leone',
                    'alphabetic_code' => 'SLL',
                    'numeric_code'    => '694',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 702,
                    'currency_name'   => 'Singapore Dollar',
                    'alphabetic_code' => 'SGD',
                    'numeric_code'    => '702',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 704,
                    'currency_name'   => 'Dong',
                    'alphabetic_code' => 'VND',
                    'numeric_code'    => '704',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 706,
                    'currency_name'   => 'Somali Shilling',
                    'alphabetic_code' => 'SOS',
                    'numeric_code'    => '706',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 710,
                    'currency_name'   => 'Rand',
                    'alphabetic_code' => 'ZAR',
                    'numeric_code'    => '710',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 728,
                    'currency_name'   => 'South Sudanese Pound',
                    'alphabetic_code' => 'SSP',
                    'numeric_code'    => '728',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 748,
                    'currency_name'   => 'Lilangeni',
                    'alphabetic_code' => 'SZL',
                    'numeric_code'    => '748',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 752,
                    'currency_name'   => 'Swedish Krona',
                    'alphabetic_code' => 'SEK',
                    'numeric_code'    => '752',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 756,
                    'currency_name'   => 'Swiss Franc',
                    'alphabetic_code' => 'CHF',
                    'numeric_code'    => '756',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 760,
                    'currency_name'   => 'Syrian Pound',
                    'alphabetic_code' => 'SYP',
                    'numeric_code'    => '760',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 764,
                    'currency_name'   => 'Baht',
                    'alphabetic_code' => 'THB',
                    'numeric_code'    => '764',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 776,
                    'currency_name'   => 'Pa’anga',
                    'alphabetic_code' => 'TOP',
                    'numeric_code'    => '776',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 780,
                    'currency_name'   => 'Trinidad and Tobago Dollar',
                    'alphabetic_code' => 'TTD',
                    'numeric_code'    => '780',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 784,
                    'currency_name'   => 'UAE Dirham',
                    'alphabetic_code' => 'AED',
                    'numeric_code'    => '784',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 788,
                    'currency_name'   => 'Tunisian Dinar',
                    'alphabetic_code' => 'TND',
                    'numeric_code'    => '788',
                    'minor_unit'      => 3,
                ],
                [
                    'id'              => 800,
                    'currency_name'   => 'Uganda Shilling',
                    'alphabetic_code' => 'UGX',
                    'numeric_code'    => '800',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 807,
                    'currency_name'   => 'Denar',
                    'alphabetic_code' => 'MKD',
                    'numeric_code'    => '807',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 818,
                    'currency_name'   => 'Egyptian Pound',
                    'alphabetic_code' => 'EGP',
                    'numeric_code'    => '818',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 826,
                    'currency_name'   => 'Pound Sterling',
                    'alphabetic_code' => 'GBP',
                    'numeric_code'    => '826',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 834,
                    'currency_name'   => 'Tanzanian Shilling',
                    'alphabetic_code' => 'TZS',
                    'numeric_code'    => '834',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 840,
                    'currency_name'   => 'US Dollar',
                    'alphabetic_code' => 'USD',
                    'numeric_code'    => '840',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 858,
                    'currency_name'   => 'Peso Uruguayo',
                    'alphabetic_code' => 'UYU',
                    'numeric_code'    => '858',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 860,
                    'currency_name'   => 'Uzbekistan Sum',
                    'alphabetic_code' => 'UZS',
                    'numeric_code'    => '860',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 882,
                    'currency_name'   => 'Tala',
                    'alphabetic_code' => 'WST',
                    'numeric_code'    => '882',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 886,
                    'currency_name'   => 'Yemeni Rial',
                    'alphabetic_code' => 'YER',
                    'numeric_code'    => '886',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 901,
                    'currency_name'   => 'New Taiwan Dollar',
                    'alphabetic_code' => 'TWD',
                    'numeric_code'    => '901',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 925,
                    'currency_name'   => 'Leone',
                    'alphabetic_code' => 'SLE',
                    'numeric_code'    => '925',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 926,
                    'currency_name'   => 'Bolívar Soberano',
                    'alphabetic_code' => 'VED',
                    'numeric_code'    => '926',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 927,
                    'currency_name'   => 'Unidad Previsional',
                    'alphabetic_code' => 'UYW',
                    'numeric_code'    => '927',
                    'minor_unit'      => 4,
                ],
                [
                    'id'              => 928,
                    'currency_name'   => 'Bolívar Soberano',
                    'alphabetic_code' => 'VES',
                    'numeric_code'    => '928',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 929,
                    'currency_name'   => 'Ouguiya',
                    'alphabetic_code' => 'MRU',
                    'numeric_code'    => '929',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 930,
                    'currency_name'   => 'Dobra',
                    'alphabetic_code' => 'STN',
                    'numeric_code'    => '930',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 931,
                    'currency_name'   => 'Peso Convertible',
                    'alphabetic_code' => 'CUC',
                    'numeric_code'    => '931',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 932,
                    'currency_name'   => 'Zimbabwe Dollar',
                    'alphabetic_code' => 'ZWL',
                    'numeric_code'    => '932',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 933,
                    'currency_name'   => 'Belarusian Ruble',
                    'alphabetic_code' => 'BYN',
                    'numeric_code'    => '933',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 934,
                    'currency_name'   => 'Turkmenistan New Manat',
                    'alphabetic_code' => 'TMT',
                    'numeric_code'    => '934',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 936,
                    'currency_name'   => 'Ghana Cedi',
                    'alphabetic_code' => 'GHS',
                    'numeric_code'    => '936',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 938,
                    'currency_name'   => 'Sudanese Pound',
                    'alphabetic_code' => 'SDG',
                    'numeric_code'    => '938',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 940,
                    'currency_name'   => 'Uruguay Peso en Unidades Indexadas (UI)',
                    'alphabetic_code' => 'UYI',
                    'numeric_code'    => '940',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 941,
                    'currency_name'   => 'Serbian Dinar',
                    'alphabetic_code' => 'RSD',
                    'numeric_code'    => '941',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 943,
                    'currency_name'   => 'Mozambique Metical',
                    'alphabetic_code' => 'MZN',
                    'numeric_code'    => '943',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 944,
                    'currency_name'   => 'Azerbaijan Manat',
                    'alphabetic_code' => 'AZN',
                    'numeric_code'    => '944',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 946,
                    'currency_name'   => 'Romanian Leu',
                    'alphabetic_code' => 'RON',
                    'numeric_code'    => '946',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 947,
                    'currency_name'   => 'WIR Euro',
                    'alphabetic_code' => 'CHE',
                    'numeric_code'    => '947',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 948,
                    'currency_name'   => 'WIR Franc',
                    'alphabetic_code' => 'CHW',
                    'numeric_code'    => '948',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 949,
                    'currency_name'   => 'Turkish Lira',
                    'alphabetic_code' => 'TRY',
                    'numeric_code'    => '949',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 950,
                    'currency_name'   => 'CFA Franc BEAC',
                    'alphabetic_code' => 'XAF',
                    'numeric_code'    => '950',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 951,
                    'currency_name'   => 'East Caribbean Dollar',
                    'alphabetic_code' => 'XCD',
                    'numeric_code'    => '951',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 952,
                    'currency_name'   => 'CFA Franc BCEAO',
                    'alphabetic_code' => 'XOF',
                    'numeric_code'    => '952',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 953,
                    'currency_name'   => 'CFP Franc',
                    'alphabetic_code' => 'XPF',
                    'numeric_code'    => '953',
                    'minor_unit'      => 0,
                ],
                [
                    'id'              => 955,
                    'currency_name'   => 'Bond Markets Unit European Composite Unit (EURCO)',
                    'alphabetic_code' => 'XBA',
                    'numeric_code'    => '955',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 956,
                    'currency_name'   => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
                    'alphabetic_code' => 'XBB',
                    'numeric_code'    => '956',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 957,
                    'currency_name'   => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
                    'alphabetic_code' => 'XBC',
                    'numeric_code'    => '957',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 958,
                    'currency_name'   => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
                    'alphabetic_code' => 'XBD',
                    'numeric_code'    => '958',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 959,
                    'currency_name'   => 'Gold',
                    'alphabetic_code' => 'XAU',
                    'numeric_code'    => '959',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 960,
                    'currency_name'   => 'SDR (Special Drawing Right)',
                    'alphabetic_code' => 'XDR',
                    'numeric_code'    => '960',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 961,
                    'currency_name'   => 'Silver',
                    'alphabetic_code' => 'XAG',
                    'numeric_code'    => '961',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 962,
                    'currency_name'   => 'Platinum',
                    'alphabetic_code' => 'XPT',
                    'numeric_code'    => '962',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 963,
                    'currency_name'   => 'Codes specifically reserved for testing purposes',
                    'alphabetic_code' => 'XTS',
                    'numeric_code'    => '963',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 964,
                    'currency_name'   => 'Palladium',
                    'alphabetic_code' => 'XPD',
                    'numeric_code'    => '964',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 965,
                    'currency_name'   => 'ADB Unit of Account',
                    'alphabetic_code' => 'XUA',
                    'numeric_code'    => '965',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 967,
                    'currency_name'   => 'Zambian Kwacha',
                    'alphabetic_code' => 'ZMW',
                    'numeric_code'    => '967',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 968,
                    'currency_name'   => 'Surinam Dollar',
                    'alphabetic_code' => 'SRD',
                    'numeric_code'    => '968',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 969,
                    'currency_name'   => 'Malagasy Ariary',
                    'alphabetic_code' => 'MGA',
                    'numeric_code'    => '969',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 970,
                    'currency_name'   => 'Unidad de Valor Real',
                    'alphabetic_code' => 'COU',
                    'numeric_code'    => '970',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 971,
                    'currency_name'   => 'Afghani',
                    'alphabetic_code' => 'AFN',
                    'numeric_code'    => '971',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 972,
                    'currency_name'   => 'Somoni',
                    'alphabetic_code' => 'TJS',
                    'numeric_code'    => '972',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 973,
                    'currency_name'   => 'Kwanza',
                    'alphabetic_code' => 'AOA',
                    'numeric_code'    => '973',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 975,
                    'currency_name'   => 'Bulgarian Lev',
                    'alphabetic_code' => 'BGN',
                    'numeric_code'    => '975',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 976,
                    'currency_name'   => 'Congolese Franc',
                    'alphabetic_code' => 'CDF',
                    'numeric_code'    => '976',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 977,
                    'currency_name'   => 'Convertible Mark',
                    'alphabetic_code' => 'BAM',
                    'numeric_code'    => '977',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 978,
                    'currency_name'   => 'Euro',
                    'alphabetic_code' => 'EUR',
                    'numeric_code'    => '978',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 979,
                    'currency_name'   => 'Mexican Unidad de Inversion (UDI)',
                    'alphabetic_code' => 'MXV',
                    'numeric_code'    => '979',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 980,
                    'currency_name'   => 'Hryvnia',
                    'alphabetic_code' => 'UAH',
                    'numeric_code'    => '980',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 981,
                    'currency_name'   => 'Lari',
                    'alphabetic_code' => 'GEL',
                    'numeric_code'    => '981',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 984,
                    'currency_name'   => 'Mvdol',
                    'alphabetic_code' => 'BOV',
                    'numeric_code'    => '984',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 985,
                    'currency_name'   => 'Zloty',
                    'alphabetic_code' => 'PLN',
                    'numeric_code'    => '985',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 986,
                    'currency_name'   => 'Brazilian Real',
                    'alphabetic_code' => 'BRL',
                    'numeric_code'    => '986',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 990,
                    'currency_name'   => 'Unidad de Fomento',
                    'alphabetic_code' => 'CLF',
                    'numeric_code'    => '990',
                    'minor_unit'      => 4,
                ],
                [
                    'id'              => 994,
                    'currency_name'   => 'Sucre',
                    'alphabetic_code' => 'XSU',
                    'numeric_code'    => '994',
                    'minor_unit'      => null,
                ],
                [
                    'id'              => 997,
                    'currency_name'   => 'US Dollar (Next day)',
                    'alphabetic_code' => 'USN',
                    'numeric_code'    => '997',
                    'minor_unit'      => 2,
                ],
                [
                    'id'              => 999,
                    'currency_name'   => 'The codes assigned for transactions where no currency is involved',
                    'alphabetic_code' => 'XXX',
                    'numeric_code'    => '999',
                    'minor_unit'      => null,
                ],
            ]
        );
    }
}
